name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17  # Changé de 11 à 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'  # Version requise par Android Gradle Plugin 8.0+
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

      # NEW: Docker build step
    - name: Build with Docker
      run: |
        docker build -t android-builder .
        docker run -v ${GITHUB_WORKSPACE}/app/build:/app/build android-builder    
