name: Android Deploy Debug

on:
  workflow_run:
    workflows: ["Android CI"]
    branches: [main]
    types: [completed]

jobs:
  deploy-debug:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Deploy Debug
        run: ./gradlew assembleDebug appDistributionUploadDebug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk