name: Android Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  BUILD_TOOLS: "34.0.0"
  TARGET_SDK: "33"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=${{ secrets.KEYSTORE_PATH }} \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Build and upload AAB
        if: github.ref == 'refs/tags/v*.*.*'
        run: |
          ./gradlew bundleRelease \
          -Pandroid.injected.signing.store.file=${{ secrets.KEYSTORE_PATH }} \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB artifact
        if: github.ref == 'refs/tags/v*.*.*'
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/*.aab

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app/build/outputs/apk/release/*.apk

      - name: Deploy to Play Store (Internal Track)
        if: github.ref == 'refs/tags/v*.*.*'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: com.your.package
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal
          status: completed